Repository kowainik/membrain, pull requests merged in 2019-07, with the labels that each got.

#34 Fix NoStartIsType error for hlint
  .travis.yml
Labels: CI

#35 Use correct prefix for kilo
  src/Membrain/Constructors.hs
  src/Membrain/Memory.hs
  src/Membrain/Units.hs
  test/Test/Memory/TypeLevel.hs
Labels: bug

#36 Some minor improvements to README
  README.md
Labels: docs

#37 Use deriving strategies
  src/Membrain/Memory.hs
  test/Doctest.hs
Labels: enhancement

#38 Preparations for the initial release
  .travis.yml
  CHANGELOG.md
  README.md
  membrain.cabal
  src/Membrain/Memory.hs
Labels: enhancement
