Repository kowainik/membrain, pull requests merged in 2019-06, with the labels that each got.

#31 [#6] Add readMemory
  src/Membrain/Memory.hs
  src/Membrain/Units.hs
  test/Doctest.hs
  test/Test/Memory/ValueLevel.hs
Labels: enhancement

#32 [#9] Add Show/Read property test
  src/Membrain/Memory.hs
  test/Spec.hs
  test/Test/Memory/Laws.hs
Labels: enhancement, tests

#33 [#13] Improve docs
  README.md
  membrain.cabal
  src/Membrain.hs
  src/Membrain/Memory.hs
  src/Membrain/Units.hs
Labels: docs
