Repository kowainik/membrain, pull requests merged in 2019-05, with the labels that each got.

#21 Upgrade to GHC-8.6.5
  .travis.yml
  CHANGELOG.md
  README.md
  membrain.cabal
  stack-8.2.2.yaml
  stack-8.4.4.yaml
  stack.yaml
Labels: refactoring

#23 [#20] Derive Show, introduce showMemory
  src/Membrain/Memory.hs
Labels: enhancement

#24 [#10] Implement type-level tests
  membrain.cabal
  stack.yaml
  test/Spec.hs
  test/Test/Memory/TypeLevel.hs
Labels: tests

#25 [#7] Impl some base functions
  membrain.cabal
  src/Membrain.hs
  src/Membrain/Base.hs
Labels: enhancement

#26 [#14] Impl Semigroup/Monoid instances, add law tests
  membrain.cabal
  src/Membrain/Memory.hs
  stack.yaml
  test/Spec.hs
  test/Test/Memory/Laws.hs
Labels: enhancement, tests

#28 [#8] Implement basic unit tests
  membrain.cabal
  stack.yaml
  test/Spec.hs
  test/Test/Memory/ValueLevel.hs
Labels: tests

#29 [#15] Implement several numeric functions
  src/Membrain/Memory.hs
Labels: enhancement

#30 [#12] Add doctest
  .ghci
  membrain.cabal
  src/Membrain/Base.hs
  src/Membrain/Constructors.hs
  src/Membrain/Memory.hs
  src/Membrain/Units.hs
  test/Doctest.hs
Labels: docs, tests
